[book]
authors = ["techzealot"]
language = "en"
multilingual = false
src = "src"
title = "build your own git"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2