[book]
authors = ["techzealot"]
language = "en"
multilingual = false
src = "src"
title = "一起玩git"

[output.html]
mathjax-support = true
site-url = "/build-your-own-git/"
git-repository-url = "https://github.com/build-your-own-x/build-your-own-git/"
edit-url-template = "https://github.com/build-your-own-x/build-your-own-git/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2